### ISSUE TITLE
Golems assigned to Gather Fresh Green Herbs not collecting

### ISSUE THREAD

**Issue by bradw82** [Jaxkr/PotionFactory#1]
Energy production is high enough that golems collect red herbs, but not green. save game status is here: 

U2FsdGVkX1+ntsyMML17s0Jf1deNakz6hVvoYMb8/N9QAV3U0Jk0v69ntoAj0lCT
TO8DV7ngedbKt2JKuH0Mmezg9DKfAki/HJHyV8xbbhOMlM1E2PhF4v5jFeoaq7rf
qw1Pox6E34i1p5np3Xps10zwowJRa4nEWvoPTDVEONbXaMLA9N4wfT7t56MWdm66
oSP9ut5/tMdpr83BmtowJHr3Mzu8fr+wtmDTkEq7R1XhjaTSbvnWZo9W7OLilrFF
KEY3K8UMXcsHu0iBBgeaU2qx4I52YF8CtNf2JKSgif0MG2BwH4PH02SBlMRxd+Tv
VjG6THhUyq1QFv7+7D/t49oeD705tB4zjwCW9O2e0JW12zAVGc8nHKyVRbwfZMac
epoid2W3U6TCYAlfNcE9TRTpnwph4qW22JBnBCZ6cgUBvIFdoGo66Gig5VNM6qL8
brERYTQarLRBu8OVBxHT+CFFFYjAYvBcptuPjbVX0gbvLx6A5MqoLV83lCPAVMzP
2Eps/Dcf9olj2Ua7Ine2EvG+k5/ezC9jA8EdaDNkZuMBs97EXEqv/nUGYOiut92A
eIjqoV77QRVV4KcWwzuYwhhzZw3KVWzQnD0+DM6i2zlikZxjiiFpoFHHHXJaXgN8
58TnAlt1A5Zn4mLqIffn8rUieihNGf3an0nxJ3OEqj2mS7lqmKfE+wGdOSb2VLyj
XJNR8YAVd8Fo4VhLmqE9+enGp3b6QDiBz9GB/c6uMXogPS9X6XXC0PTly2U3P6by
vnuuv75yjrqudB9fIPFZkAANT3RYONpAaJQgol63ZNKHJm0eky3em5UK3NsyRd8a
jUA8cr99dZH9Px1TIMO0v4TmUTvF7w+v1KbwfDn8HzuUkaCRlXEkWg2kpALHWICX
9yZDvWQd9cFt7CZQEgvj4kh9qj8qvcHKinNdlLqMtJoq4nVTqDYEelYlbm+Q7uUh
yVwRrPCc+rwPkPE03u9+t5RT...gRuBn609Rrc10AsQJOkzcdNkHhKW2y1sjsEwf2msQafAEIIfwG73zg9aSAqlNJ1
cnN/fISnnzyJ0Xyn34Zuj3Sd+oSoa3xt5cFp8lLEHhtcsshE3ySqIODlREdYA/gR
x0+cOQMyJOFVWZEdatnsfVJ/8QZkp0BsHWH9jNYOHYN+lMVEFL1SMai0SwVh9glC
+gI1pqEmFLogB8S5nHzDsofQGLHjfctgPxC8dK7wimVHM0nlrPvBFiUTNyTBWX0K
GNI/+x6VouS1P+oQW2FLUVtiLxCahu5M9M4hmT+AJMVwiBMKi/wGfIGOB8VCMubB
cEn8OGs/MNVKIvlGV8wvweGdPlVglpw/UtqZ9AO/FRUcBXtuEszyRpYCn6dQtgnd
NZFech8RX6gmUqSK4ZHDU0f1p6jWEgRzOa5opMdicPorbmX52e6nYp31/PR2DRex
dTg+ZnD9GL+hUUZAwiEviZ37F5JJeY3KS35ssWKwFbF8tS6V8JokL+aKdKhbAZhj
h85z19FD8kHhcQaUuHRYkKE8oK0l1grynHPvsq+lhlwcPQh77kTsDdKFL4va5anP
mdQqdJShH7Z/5Qu54qO5bPHNIIny8Fsit4lF1LCNlu9f2gHDZGP4SbeWP/6lYpOg
2k47kYlczQ8zhcGfO5zsN3Jd0TK11DtNG9crTwR+l1YvkHhHZxI2lPXwPh+sG7Ky
TcbKDGVCr8X1SGaE/KIadk7kwfH2UsubWWXVlLKjdotwAddZPrZzg2G2b844gSK6
D+5UWZutxqBJ8xcGbuEjpYq7oLKGFcG+qtoQ6rYuUG+25Eze8k9+t643+w3kXGP9
OspFk9A5dHhlSyfVvvisazjz27nhb9fXR/zSQRfdDQvDsOsO73t1o8bkuYwNmM3r
1LkZI6dvjarmPeyx6HmueeyJ0YlN1XllIdWSFHaC95g5EyOitt/EdIsD6RYloV3z
j1dHnw+DK0fLhlmiyENeaA==

**Comment by bradw82** [comment]
Nope, I'm an idiot. It was an energy issue. Sorry for the erroneous bug report!

**Comment by Jaxkr** [comment]
It's alright! Thanks for the good bug report (included savedata 👍 )
