### ISSUE TITLE
Animations Slowing down browser.

### ISSUE THREAD

**Issue by MubarakHAlketbi** [Jaxkr/PotionFactory#4]
Hello,

is it possible to give us an option to disable the flying icons, at high rate of production and energy farming the browser becomes slow and hangs.

**Comment by Jaxkr** [comment]
This will be added in the next update.

**Comment by Jaxkr** [comment]
fixed in https://github.com/Jaxkr/PotionFactory/commit/5c7d8b56df85124bfe2c19840d5dfbb33ac88d7a
