### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by WowSporkles** [Jaxkr/PotionFactory#5]
The game works wellish on my iPhone 6. The only thing I am incapable of doing is dragging ingredients. Perhaps add a mobile setting where you click on one ingredient and then click on another to combine them, rather than dragging.

**Comment by Jaxkr** [comment]
At the moment, the game is not intended for mobile devices. It would basically require a complete remake for mobile. Sorry. :(

**Comment by Jaxkr** [comment]
Well, #6 proposed just adding touch support though a jquery library. This works, but it still doesn't make the game good on mobile. 😜
